force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>WB Exception Log</label>
    <nameField>
        <displayFormat>Exception {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WB Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Line_Numer__c.field-meta.xml
<CustomField>
    <fullName>Exception_Line_Numer__c</fullName>
    <label>Exception Line Numer</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ExceptionLog.cls
public with sharing class ExceptionLog {
    public static void exception(String Response, String classname, String methodname,Integer exceptionLine){
        try {
            Exception_Log__c error = new Exception_Log__c();
            error.Exception_Message__c = Response;
            error.Class_Name__c = classname;
            error.Method_Name__c = methodname;
            error.Exception_Line_Numer__c = exceptionLine;
            insert error;
        } catch (Exception e) {
            System.debug('Error in ExceptionLog ..' + e.getMessage() + '\n' + e +'\n Exception line no : '+ e.getLineNumber());
        }
    }
}